#!/bin/bash -e
cd fairphone_os
repo sync
curl http://code.fairphone.com/downloads/FP2/blobs/fp2-sibon-2.0.1-blobs.tgz -o fp2-sibon-2.0.1-blobs.tgz
tar zxvf fp2-sibon-2.0.1-blobs.tgz
sh fp2-sibon-2.0.1-blobs.sh
. build/envsetup.sh
choosecombo 1 FP2 2
make
fastboot flashall -w
